### ISSUE TITLE
Challenge #6 read-only file system error

### ISSUE THREAD

**Issue by nrnatesh** [ibiem-master/community#25]
I am trying to run the QIIME python script on the map file by `cd $DATA_DIR` and running `validate_mapping_file.py -m ibiem_2017_map_v3.txt` and am receiving the following error:

```
 Traceback (most recent call last):
   File "/usr/local/bin/validate_mapping_file.py", line 162, in <module>
     main()
   File "/usr/local/bin/validate_mapping_file.py", line 158, in main
     disable_primer_check, added_demultiplex_field, suppress_html)
   File "/usr/local/lib/python2.7/dist-packages/qiime/check_id_map.py", line 106, in check_mapping_file
     html_f = open(output_html, "w")
 IOError: [Errno 30] Read-only file system: './/ibiem_2017_map_v3.html'
```

 chmod requires sudo for changing these files to writeable/executable. I appreciate any help. Thank you!

**Comment by granek** [comment]
`chmod` does not always require `sudo`, it only requires `sudo` for files (or directories) which you don't own.  I promise you that you do not need `sudo` for this class!  Anyway, you need stronger magic than `chmod` to write to the directory you are trying to write to because, as the error message tells you, you are trying to write to a "Read-only **file system**".  

In the IBIEM environment, if you get an error message that tells you you are trying to write to a file or directory that you don't have permissions to, it means one of the following:

1. You are trying to write to a file/directory that **you** made read-only, in which case you can change the permissions yourself.  But before you use `chmod` you should first think about whether that is the right thing to do, because you probably set the destination as read-only for a good reason.

2. You are trying to write to a file/directory that **I** made read-only, in which case it is **definitely not** the right thing to do, because I **definitely** set the destination as read-only for a good reason.

What directory is your code trying to write to?  Is it an appropriate place?
